/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRONTEND;

import DAO.clsQuerys;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class frmCrearCita extends javax.swing.JFrame {

    /**
     * Creates new form frmCrearCita
     */
    public frmCrearCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ctFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ctPersonaje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ctNombreE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        btCrearCita = new javax.swing.JButton();
        btRegreso = new javax.swing.JButton();
        btCita1 = new javax.swing.JButton();
        ctNombreA1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Magneto", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREAR CITA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("FECHA O DIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 20));

        ctFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctFechaActionPerformed(evt);
            }
        });
        getContentPane().add(ctFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 220, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PERSONAJE DESEADO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 20));

        ctPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPersonajeActionPerformed(evt);
            }
        });
        getContentPane().add(ctPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("EXPERTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 20));

        ctNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNombreEActionPerformed(evt);
            }
        });
        getContentPane().add(ctNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CODIGO CITA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, 20));

        ctCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(ctCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 220, -1));

        btCrearCita.setBackground(new java.awt.Color(153, 153, 153));
        btCrearCita.setText("CREAR CITA");
        btCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btCrearCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 40));

        btRegreso.setBackground(new java.awt.Color(153, 153, 153));
        btRegreso.setText("REGRESAR A LA GALAXIA INICIAL");
        btRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(btRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 40));

        btCita1.setBackground(new java.awt.Color(153, 153, 153));
        btCita1.setText("VER CITAS");
        btCita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCita1ActionPerformed(evt);
            }
        });
        getContentPane().add(btCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 40));

        ctNombreA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNombreA1ActionPerformed(evt);
            }
        });
        getContentPane().add(ctNombreA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 220, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("NOMBRE DEL AFICIONADO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 20));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ESPACIO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctFechaActionPerformed

    private void ctPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPersonajeActionPerformed

    private void ctNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNombreEActionPerformed

    private void ctCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCodigoActionPerformed

    private void btRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresoActionPerformed
        frmInicio objVentana = new frmInicio();
            objVentana.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btRegresoActionPerformed

    private void btCita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCita1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCita1ActionPerformed

    private void btCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearCitaActionPerformed
       clsQuerys objQuery = new clsQuerys();


       if( 
               objQuery.fncIngresoCita(ctCodigo.getText(), ctNombreA1.getText(), ctFecha.getText(), ctPersonaje.getText(), ctNombreE.getText()  )
               ==1){
           JOptionPane.showMessageDialog(null, "REGISTRO DE CITA REALIZADO CORRECTAMENTE.", "REGISTRO DE CITA", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(null, "REGISTRO DE CITA NO REALIZADO.", "REGISTRO DE CITA", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btCrearCitaActionPerformed

    private void ctNombreA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNombreA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNombreA1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ctCodigo.setText("");
        ctFecha.setText("");
        ctNombreA1.setText("");
        ctNombreE.setText("");
        ctPersonaje.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCita1;
    private javax.swing.JButton btCrearCita;
    private javax.swing.JButton btRegreso;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JTextField ctFecha;
    private javax.swing.JTextField ctNombreA1;
    private javax.swing.JTextField ctNombreE;
    private javax.swing.JTextField ctPersonaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
