/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRONTEND;

import BACKEND.clsGeneral;
import DAO.clsQuerys;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class frmPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form frmPersonaje
     */
    public frmPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ctPersonaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ctPelicula2 = new javax.swing.JTextField();
        ctPelicula3 = new javax.swing.JTextField();
        ctPelicula4 = new javax.swing.JTextField();
        ctPelicula5 = new javax.swing.JTextField();
        ctPelicula6 = new javax.swing.JTextField();
        ctPelicula7 = new javax.swing.JTextField();
        ctPelicula8 = new javax.swing.JTextField();
        ctPelicula = new javax.swing.JTextField();
        ctEditar = new javax.swing.JButton();
        ctEliminar = new javax.swing.JButton();
        ctVer = new javax.swing.JButton();
        ctCita = new javax.swing.JButton();
        btCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Magneto", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERSONAJES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOMBRE DEL PERSONAJE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));
        getContentPane().add(ctPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PELICULAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 370, -1));
        getContentPane().add(ctPelicula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 380, -1));
        getContentPane().add(ctPelicula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, -1));
        getContentPane().add(ctPelicula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 380, -1));
        getContentPane().add(ctPelicula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 380, -1));
        getContentPane().add(ctPelicula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 380, -1));
        getContentPane().add(ctPelicula7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 380, -1));

        ctPelicula8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPelicula8ActionPerformed(evt);
            }
        });
        getContentPane().add(ctPelicula8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 380, -1));
        getContentPane().add(ctPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, -1));

        ctEditar.setBackground(new java.awt.Color(153, 153, 153));
        ctEditar.setText("EDITAR");
        ctEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctEditarActionPerformed(evt);
            }
        });
        getContentPane().add(ctEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        ctEliminar.setBackground(new java.awt.Color(153, 153, 153));
        ctEliminar.setText("ELIMINAR");
        ctEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(ctEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        ctVer.setBackground(new java.awt.Color(153, 153, 153));
        ctVer.setText("VER");
        ctVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctVerActionPerformed(evt);
            }
        });
        getContentPane().add(ctVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        ctCita.setBackground(new java.awt.Color(153, 153, 153));
        ctCita.setText("REGRESAR A LA PRIMERA GALAXIA");
        ctCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCitaActionPerformed(evt);
            }
        });
        getContentPane().add(ctCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 410, -1));

        btCrear.setBackground(new java.awt.Color(153, 153, 153));
        btCrear.setText("CREAR");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CODIGO PERSONAJE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));
        getContentPane().add(ctCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ESPACIO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctPelicula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPelicula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPelicula8ActionPerformed

    private void ctCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCitaActionPerformed
        frmInicio objVentana = new frmInicio();
            objVentana.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_ctCitaActionPerformed

    private void ctVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctVerActionPerformed
        
    }//GEN-LAST:event_ctVerActionPerformed

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
       clsQuerys objQuery = new clsQuerys();


       if( 
               objQuery.fncIngresoPersonaje (ctPersonaje.getText(), ctPelicula.getText(), ctPelicula2.getText(), ctPelicula3.getText(),ctPelicula4.getText() ,ctPelicula5.getText() , ctPelicula6.getText(), ctPelicula7.getText(), ctPelicula8.getText(),ctCodigo.getText())
               ==1){
           JOptionPane.showMessageDialog(null, "REGISTRO DE PERSONAJE REALIZADO CORRECTAMENTE.", "REGISTRO DE PERSONAJE", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(null, "REGISTRO DE PERSONAJE NO REALIZADO.", "REGISTRO DE PERSONAJE", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btCrearActionPerformed

    private void ctEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctEditarActionPerformed
        clsGeneral objPersonaje = new clsGeneral();
          clsQuerys objQuery = new clsQuerys();
          objPersonaje.setCODIGO_PERSONAJE(ctCodigo.getText());
          objPersonaje.setNOMBRE_PERSONAJE(  ctPersonaje.getText()     );
          objPersonaje.setPELICULA1( ctPelicula.getText());
          objPersonaje.setPELICULA2(  ctPelicula2.getText());
          objPersonaje.setPELICULA3(  ctPelicula3.getText());
          objPersonaje.setPELICULA4(  ctPelicula4.getText());
          objPersonaje.setPELICULA5(  ctPelicula5.getText());
          objPersonaje.setPELICULA6(  ctPelicula6.getText());
          objPersonaje.setPELICULA7(  ctPelicula7.getText());
          objPersonaje.setPELICULA8(  ctPelicula8.getText());
          if (objQuery.fncEditarPersonaje(objPersonaje)==1){
               JOptionPane.showMessageDialog(null, "REGISTRO DE PERSONAJE MODIFICADO CORRECTAMENTE.", "REGISTRO DE PERSONAJE", JOptionPane.INFORMATION_MESSAGE);
          }else{
               JOptionPane.showMessageDialog(null, "REGISTRO DE PERSONAJE SIN MODIFICAR.", "REGISTRO DE PERSONAJE", JOptionPane.ERROR_MESSAGE);
          }
    }//GEN-LAST:event_ctEditarActionPerformed

    private void ctEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctEliminarActionPerformed
       clsQuerys objQuery = new clsQuerys();




       if(   objQuery.fncEliminarPersonaje(   ctCodigo.getText()   )  == 1){
           JOptionPane.showMessageDialog(null, "REGISTRO DE PERSONAJE ELIMINADo CORRECTAMENTE.", "REGISTRO DE PERSONAJE", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(null, "EL REGISTRO DE PERSONAJE NO SE PUDO ELIMINAR.", "REGISTRO DE PERSONAJE", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_ctEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ctCodigo.setText("");
        ctPersonaje.setText("");
        ctPelicula.setText("");
        ctPelicula2.setText("");
        ctPelicula3.setText("");
        ctPelicula4.setText("");
        ctPelicula5.setText("");
        ctPelicula6.setText("");
        ctPelicula7.setText("");
        ctPelicula8.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.JButton ctCita;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JButton ctEditar;
    private javax.swing.JButton ctEliminar;
    private javax.swing.JTextField ctPelicula;
    private javax.swing.JTextField ctPelicula2;
    private javax.swing.JTextField ctPelicula3;
    private javax.swing.JTextField ctPelicula4;
    private javax.swing.JTextField ctPelicula5;
    private javax.swing.JTextField ctPelicula6;
    private javax.swing.JTextField ctPelicula7;
    private javax.swing.JTextField ctPelicula8;
    private javax.swing.JTextField ctPersonaje;
    private javax.swing.JButton ctVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
